"""
Database Models for AI Interview System
Uses SQLAlchemy ORM (Python's equivalent to Drizzle)
"""

from sqlalchemy import Column, Integer, String, Text, Float, DateTime, ForeignKey, Boolean, JSON
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime

# Base class for all models
Base = declarative_base()


class User(Base):
    """
    Stores user information collected in Personal Info tab
    """
    __tablename__ = 'users'
    
    # Primary Key
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Personal Details
    name = Column(String(100), nullable=False)
    email = Column(String(100), unique=True, nullable=False)
    phone = Column(String(20), nullable=True)
    
    # Professional Details
    target_role = Column(String(100), nullable=False)
    domain = Column(String(100), nullable=False)
    skills = Column(Text, nullable=False)
    experience_years = Column(Integer, nullable=False)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    interviews = relationship('Interview', back_populates='user', cascade='all, delete-orphan')
    
    def __repr__(self):
        return f"<User(id={self.id}, name='{self.name}', role='{self.target_role}')>"


class Interview(Base):
    """
    Stores each interview session
    """
    __tablename__ = 'interviews'
    
    # Primary Key
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Foreign Key
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    
    # Interview Details
    status = Column(String(20), default='in_progress')
    overall_score = Column(Float, nullable=True)
    
    # Timestamps
    started_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)
    
    # Relationships
    user = relationship('User', back_populates='interviews')
    questions = relationship('Question', back_populates='interview', cascade='all, delete-orphan')
    responses = relationship('Response', back_populates='interview', cascade='all, delete-orphan')
    feedback = relationship('Feedback', back_populates='interview', uselist=False, cascade='all, delete-orphan')
    
    def __repr__(self):
        return f"<Interview(id={self.id}, user_id={self.user_id}, status='{self.status}')>"


class Question(Base):
    """
    Stores questions generated by Gemini for each interview
    """
    __tablename__ = 'questions'
    
    # Primary Key
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Foreign Key
    interview_id = Column(Integer, ForeignKey('interviews.id'), nullable=False)
    
    # Question Details
    question_number = Column(Integer, nullable=False)
    question_text = Column(Text, nullable=False)
    reference_answer = Column(Text, nullable=False)
    expected_keywords = Column(JSON, nullable=True)
    difficulty_level = Column(String(20), nullable=True)
    
    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    interview = relationship('Interview', back_populates='questions')
    response = relationship('Response', back_populates='question', uselist=False, cascade='all, delete-orphan')
    
    def __repr__(self):
        return f"<Question(id={self.id}, number={self.question_number})>"


class Response(Base):
    """
    Stores user's response to each question
    """
    __tablename__ = 'responses'
    
    # Primary Key
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Foreign Keys
    interview_id = Column(Integer, ForeignKey('interviews.id'), nullable=False)
    question_id = Column(Integer, ForeignKey('questions.id'), nullable=False)
    
    # User's Answer
    transcript = Column(Text, nullable=True)
    
    # Audio Metrics
    audio_duration = Column(Float, nullable=True)
    average_pitch = Column(Float, nullable=True)
    pitch_variation = Column(Float, nullable=True)
    speaking_rate = Column(Float, nullable=True)
    pause_count = Column(Integer, nullable=True)
    filler_words_count = Column(Integer, nullable=True)
    sentiment_score = Column(Float, nullable=True)
    sentiment_label = Column(String(20), nullable=True)
    grammar_score = Column(Float, nullable=True)
    
    # Video Metrics
    eye_contact_score = Column(Float, nullable=True)
    gaze_violations = Column(Integer, nullable=True)
    violation_timestamps = Column(JSON, nullable=True)
    head_stability_score = Column(Float, nullable=True)
    
    # Content Analysis
    keyword_match_score = Column(Float, nullable=True)
    matched_keywords = Column(JSON, nullable=True)
    semantic_similarity = Column(Float, nullable=True)
    
    # Individual Question Score
    question_score = Column(Float, nullable=True)
    
    # Metadata
    recorded_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    interview = relationship('Interview', back_populates='responses')
    question = relationship('Question', back_populates='response')
    
    def __repr__(self):
        return f"<Response(id={self.id}, question_id={self.question_id}, score={self.question_score})>"


class Feedback(Base):
    """
    Stores final feedback and recommendations
    """
    __tablename__ = 'feedback'
    
    # Primary Key
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Foreign Key
    interview_id = Column(Integer, ForeignKey('interviews.id'), nullable=False)
    
    # Overall Scores
    overall_score = Column(Float, nullable=False)
    content_score = Column(Float, nullable=False)
    audio_score = Column(Float, nullable=False)
    video_score = Column(Float, nullable=False)
    
    # Detailed Feedback
    strengths = Column(Text, nullable=True)
    weaknesses = Column(Text, nullable=True)
    recommendations = Column(Text, nullable=True)
    
    # Per-Question Breakdown
    question_wise_analysis = Column(JSON, nullable=True)
    
    # Metadata
    generated_at = Column(DateTime, default=datetime.utcnow)
    
    # Relationships
    interview = relationship('Interview', back_populates='feedback')
    
    def __repr__(self):
        return f"<Feedback(id={self.id}, interview_id={self.interview_id}, score={self.overall_score})>"


def create_tables(engine):
    """
    Creates all tables in the database
    """
    Base.metadata.create_all(engine)
    print("✅ All tables created successfully!")


def drop_tables(engine):
    """
    Drops all tables - USE ONLY IN DEVELOPMENT!
    """
    Base.metadata.drop_all(engine)
    print("⚠️ All tables dropped!")